#
# Even Fibonacci numbers
# Problem 1
#
# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.
#
import time

def time_execution(code):
    start = time.clock()
    result = eval(code)
    run_time = time.clock() - start
    return result, run_time

def problem00002(n):
	sum = 0
	a, b = 0, 1
	while True:
		a, b = b, a + b
		if a % 2 == 0:
			sum += a
		if b > n:
			break
	return sum

print(time_execution("problem00002(4000000)"))
